### ISSUE TITLE
Build Failure on v0.9.0

### ISSUE THREAD

**Issue by jramapuram** [Landoop/schema-registry-ui#45]
Can't seem to install v0.9.0:

```bash
(.venv) ➜  schema-registry-ui git:(f15128c) npm install        

> schema-registry-ui@0.9.0 postinstall /home/jramapuram/Dropbox/projects/schema-registry-ui
> bower install

(node:17514) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
bower angular-ui-ace#bower  not-cached https://github.com/angular-ui/ui-ace.git#bower
bower angular-ui-ace#bower     resolve https://github.com/angular-ui/ui-ace.git#bower
bower ace-diff#*            not-cached https://github.com/gad2103/ace-diff.git#*
bower ace-diff#*               resolve https://github.com/gad2103/ace-diff.git#*
bower Stuk/jszip-utils=Stuk/jszip-utils#*       not-cached https://github.com/Stuk/jszip-utils.git#*
bower Stuk/jszip-utils=Stuk/jszip-utils#*          resolve https://github.com/Stuk/jszip-utils.git#*
bower Stuk/jszip=Stuk/jszip#*                   not-cached https://github.com/Stuk/jszip.git#*
bower Stuk/jszip=Stuk/jszip#*                      resolve https://github.com/Stuk/jszip.git#*
bower angular#1.5.9                                 cached https://github.com/angular/bower-angular.git#1.5.9
bower angular#1.5.9                               validate 1.5.9 against https://github.com/angular/bower-angular.git#1.5.9
bower angular-route#1.5.9                           cached https://github.com/angular/bower-angular-route.git#1.5.9
bower angular-route#1.5.9                         validate 1.5.9 against https://github.com/angular/bower-angular-route.git#1.5.9
bower angular-aria#1.5.9                            cached https://github.com/angular/bower-angular-aria.git#1.5.9
bower angular-aria#1.5.9                          validate 1.5.9 against https://github.com/angular/bower-angular-aria.git#1.5.9
bower angular-animate#1.5.9                         cached https://github.com/angular/bower-angular-animate.git#1.5.9
bower angular-animate#1.5.9                       validate 1.5.9 against https://github.com/angular/bower-angular-animate.git#1.5.9
bower bootstrap#^3.3.6                              cached https://github.com/twbs/bootstrap.git#3.3.7
bower bootstrap#^3.3.6                            validate 3.3.7 against https://github.com/twbs/bootstrap.git#^3.3.6
bower angular-material#^1.0.9                       cached https://github.com/angular/bower-material.git#1.1.3
bower angular-material#^1.0.9                     validate 1.1.3 against https://github.com/angular/bower-material.git#^1.0.9
bower angular-spinner#^0.8.1                        cached https://github.com/Attrash-Islam/bower-angular-spinner.git#0.8.1
bower angular-spinner#^0.8.1                      validate 0.8.1 against https://github.com/Attrash-Islam/bower-angular-spinner.git#^0.8.1
bower angular-sanitize#1.5.9                        cached https://github.com/angular/bower-angular-sanitize.git#1.5.9
bower angular-sanitize#1.5.9                      validate 1.5.9 against https://github.com/angular/bower-angular-sanitize.git#1.5.9
bower font-awesome#^4.6.3                           cached https://github.com/FortAwesome/Font-Awesome.git#4.7.0
bower font-awesome#^4.6.3                         validate 4.7.0 against https://github.com/FortAwesome/Font-Awesome.git#^4.6.3
bower angularUtils-pagination#^0.11.1               cached https://github.com/michaelbromley/angularUtils-pagination.git#0.11.1
bower angularUtils-pagination#^0.11.1             validate 0.11.1 against https://github.com/michaelbromley/angularUtils-pagination.git#^0.11.1
bower angular-material-data-table#^0.10.9           cached https://github.com/daniel-nagy/md-data-table.git#0.10.10
bower angular-material-data-table#^0.10.9         validate 0.10.10 against https://github.com/daniel-nagy/md-data-table.git#^0.10.9
bower angular-diff-match-patch#^0.2.4               cached https://github.com/amweiss/angular-diff-match-patch.git#0.2.4
bower angular-diff-match-patch#^0.2.4             validate 0.2.4 against https://github.com/amweiss/angular-diff-match-patch.git#^0.2.4
bower angular-json-tree#^1.0.1                      cached https://github.com/awendland/angular-json-tree.git#1.0.1
bower angular-json-tree#^1.0.1                    validate 1.0.1 against https://github.com/awendland/angular-json-tree.git#^1.0.1
bower ace-diff#*                                  checkout master
bower angular-ui-ace#bower                        checkout bower
bower angular-ui-ace#bower                    invalid-meta angular-ui-ace is missing "ignore" entry in bower.json
bower angular-ui-ace#bower                        resolved https://github.com/angular-ui/ui-ace.git#36844ff7c0
bower ace-diff#*                                  resolved https://github.com/gad2103/ace-diff.git#917afdc876
bower Stuk/jszip-utils=Stuk/jszip-utils#*           ENOENT ENOENT: no such file or directory, mkdir '/tmp/jramapuram/bower/Stuk/jszip-utils=Stuk/jszip-utils-17514-2hNk2k'

Stack trace:
Error: ENOENT: no such file or directory, mkdir '/tmp/jramapuram/bower/Stuk/jszip-utils=Stuk/jszip-utils-17514-2hNk2k'

Console trace:
Trace
    at StandardRenderer.error (/home/jramapuram/Dropbox/projects/schema-registry-ui/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/home/jramapuram/Dropbox/projects/schema-registry-ui/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:191:7)
    at Logger.emit (/home/jramapuram/Dropbox/projects/schema-registry-ui/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/jramapuram/Dropbox/projects/schema-registry-ui/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/home/jramapuram/Dropbox/projects/schema-registry-ui/node_modules/q/q.js:797:24)
    at /home/jramapuram/Dropbox/projects/schema-registry-ui/node_modules/q/q.js:823:30
    at Promise.when (/home/jramapuram/Dropbox/projects/schema-registry-ui/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/home/jramapuram/Dropbox/projects/schema-registry-ui/node_modules/q/q.js:741:41)

System info:
Bower version: 1.3.12
Node version: 7.7.1
OS: Linux 4.9.13-1-MANJARO x64

npm ERR! Linux 4.9.13-1-MANJARO
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! schema-registry-ui@0.9.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the schema-registry-ui@0.9.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the schema-registry-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs schema-registry-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls schema-registry-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jramapuram/.npm/_logs/2017-03-13T12_30_36_944Z-debug.lo
```

```bash
(.venv) ➜  schema-registry-ui git:(f15128c) npm --version
4.3.0
(.venv) ➜  schema-registry-ui git:(f15128c) node --version
v7.7.1
```

I even updated bower systemwide, but it doesn't seem to get used?
```bash
(.venv) ➜  schema-registry-ui git:(f15128c) sudo npm install -g bower
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
/usr/lib
└── bower@1.8.0 

(.venv) ➜  schema-registry-ui git:(f15128c) bower

Usage:

    bower <command> [<args>] [<options>]
Commands:

    cache                   Manage bower cache
    help                    Display help information about Bower
    home                    Opens a package homepage into your favorite browser
    info                    Info of a particular package
    init                    Interactively create a bower.json file
    install                 Install a package locally
    link                    Symlink a package folder
    list                    List local packages - and possible updates
    login                   Authenticate with GitHub and store credentials
    lookup                  Look up a single package URL by name
    prune                   Removes local extraneous packages
    register                Register a package
    search                  Search for packages by name
    update                  Update a local package
    uninstall               Remove a local package
    unregister              Remove a package from the registry
    version                 Bump a package version
Options:

    -f, --force             Makes various commands more forceful
    -j, --json              Output consumable JSON
    -l, --loglevel          What level of logs to report
    -o, --offline           Do not hit the network
    -q, --quiet             Only output important information
    -s, --silent            Do not output anything, besides errors
    -V, --verbose           Makes output more verbose
    --allow-root            Allows running commands as root
    -v, --version           Output Bower version
    --no-color              Disable colors
See 'bower help <command>' for more information on a specific command.
(.venv) ➜  schema-registry-ui git:(f15128c) bower --version
1.8.0
```

I even tried setting up a nodeenv and that resulted in the same situation.

**Comment by jglambed** [comment]
I think the cause of your issue is that bower is not installed in you computer.
Try to install bower first by running `$ npm install -g bower` and the nbuild again by using `npm install`. This should work.

Please let us know if that helps

**Comment by jramapuram** [comment]
Yup, this was my fault. Needed to install bower as suggested and call to bower install in the root of the repo
